/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #          MSP stack          #  .data  #  .bss  #       newlib heap       #
 * # Reserved by _Stack_Size     #         #        #                         #
 * ############################################################################
 * ^-- RAM start        _estack--^    __start_HEAP--^            __end_HEAP --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t __start_HEAP; /* Symbol defined in the linker script */
  extern uint8_t __end_HEAP;   /* Symbol defined in the linker script */
  const uint8_t *max_heap = (uint8_t *)&__end_HEAP;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &__start_HEAP;
  }

  /* Protect heap from growing over the RAM end */
  if ((__sbrk_heap_end + incr) > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}

