tlv_enabled: false
offset_size: 16
mfg_page_size: 98
mfg_offsets:
  SID_PAL_MFG_STORE_MAGIC:
    start: 0
    end: 1
  SID_PAL_MFG_STORE_VERSION:
    start: 1
    end: 2
  SID_PAL_MFG_STORE_SERIAL_NUM:
    start: 2
    end: 4
  SID_PAL_MFG_STORE_SMSN:
    start: 4
    end: 6
  SID_PAL_MFG_STORE_APID:
    start: 6
    end: 7
  SID_PAL_MFG_STORE_APP_PUB_ED25519:
    start: 7
    end: 9
  SID_PAL_MFG_STORE_DEVICE_PRIV_ED25519:
    start: 9
    end: 11
  SID_PAL_MFG_STORE_DEVICE_PUB_ED25519:
    start: 11
    end: 13
  SID_PAL_MFG_STORE_DEVICE_PUB_ED25519_SIGNATURE:
    start: 13
    end: 17
  SID_PAL_MFG_STORE_DEVICE_PRIV_P256R1:
    start: 17
    end: 19
  SID_PAL_MFG_STORE_DEVICE_PUB_P256R1:
    start: 19
    end: 23
  SID_PAL_MFG_STORE_DEVICE_PUB_P256R1_SIGNATURE:
    start: 23
    end: 27
  SID_PAL_MFG_STORE_DAK_PUB_ED25519:
    start: 27
    end: 29
  SID_PAL_MFG_STORE_DAK_PUB_ED25519_SIGNATURE:
    start: 29
    end: 33
  SID_PAL_MFG_STORE_DAK_ED25519_SERIAL:
    start: 33
    end: 34
  SID_PAL_MFG_STORE_DAK_PUB_P256R1:
    start: 34
    end: 38
  SID_PAL_MFG_STORE_DAK_PUB_P256R1_SIGNATURE:
    start: 38
    end: 42
  SID_PAL_MFG_STORE_DAK_P256R1_SERIAL:
    start: 42
    end: 43
  SID_PAL_MFG_STORE_PRODUCT_PUB_ED25519:
    start: 43
    end: 45
  SID_PAL_MFG_STORE_PRODUCT_PUB_ED25519_SIGNATURE:
    start: 45
    end: 49
  SID_PAL_MFG_STORE_PRODUCT_ED25519_SERIAL:
    start: 49
    end: 50
  SID_PAL_MFG_STORE_PRODUCT_PUB_P256R1:
    start: 50
    end: 54
  SID_PAL_MFG_STORE_PRODUCT_PUB_P256R1_SIGNATURE:
    start: 54
    end: 58
  SID_PAL_MFG_STORE_PRODUCT_P256R1_SERIAL:
    start: 58
    end: 59
  SID_PAL_MFG_STORE_MAN_PUB_ED25519:
    start: 59
    end: 61
  SID_PAL_MFG_STORE_MAN_PUB_ED25519_SIGNATURE:
    start: 61
    end: 65
  SID_PAL_MFG_STORE_MAN_ED25519_SERIAL:
    start: 65
    end: 66
  SID_PAL_MFG_STORE_MAN_PUB_P256R1:
    start: 66
    end: 70
  SID_PAL_MFG_STORE_MAN_PUB_P256R1_SIGNATURE:
    start: 70
    end: 74
  SID_PAL_MFG_STORE_MAN_P256R1_SERIAL:
    start: 74
    end: 75
  SID_PAL_MFG_STORE_SW_PUB_ED25519:
    start: 75
    end: 77
  SID_PAL_MFG_STORE_SW_PUB_ED25519_SIGNATURE:
    start: 77
    end: 81
  SID_PAL_MFG_STORE_SW_ED25519_SERIAL:
    start: 81
    end: 82
  SID_PAL_MFG_STORE_SW_PUB_P256R1:
    start: 82
    end: 86
  SID_PAL_MFG_STORE_SW_PUB_P256R1_SIGNATURE:
    start: 86
    end: 90
  SID_PAL_MFG_STORE_SW_P256R1_SERIAL:
    start: 90
    end: 91
  SID_PAL_MFG_STORE_AMZN_PUB_ED25519:
    start: 91
    end: 93
  SID_PAL_MFG_STORE_AMZN_PUB_P256R1:
    start: 93
    end: 97
